### ISSUE TITLE
pocket-node list Issue 

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-node#52]
when going through the documentation, hit a issue of listing plugins. error i received was: 

computer specs: (Mac OSX Mojave)

pocket-node list
info: Listing plugins
Error reloading config file: /usr/local/lib/node_modules/pocket-node/src/configuration/plugins.json
SyntaxError: /usr/local/lib/node_modules/pocket-node/src/configuration/plugins.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/pocket-node/node_modules/jsonfile/index.js:33:18
    at /usr/local/lib/node_modules/pocket-node/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
info: No plugins installed

**Comment by luyzdeleon** [comment]
Thanks for the detailed report, will take a look at this.
