### ISSUE TITLE
pocket-node install (pnp-eth)

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-node#53]
when installing the ETH plugin, it says that it has installed successfully, but threw the same errors in issue #52.  

pocket-node install pnp-eth
info: Installing: pnp-eth
pnp-eth plugin installed succesfully
Error reloading config file: /usr/local/lib/node_modules/pocket-node/src/configuration/plugins.json
SyntaxError: /usr/local/lib/node_modules/pocket-node/src/configuration/plugins.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/pocket-node/node_modules/jsonfile/index.js:33:18
    at /usr/local/lib/node_modules/pocket-node/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/pocket-node/node_modules/jsonfile-updater/index.js:37:24
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)

**Comment by luyzdeleon** [comment]
Maybe try checking your disk permissions? Sometimes node acts up with file systems when run with `sudo`

**Comment by jeremybeal11** [comment]
i have, and the same flag comes up.

**Comment by luyzdeleon** [comment]
Did you install the package globally from NPM or are you running it from source?

**Comment by jeremybeal11** [comment]
globally using NPM

**Comment by luyzdeleon** [comment]
Thanks for your input, I found the issue here:

https://github.com/pokt-network/pocket-node/blob/master/src/config-file-manager.js#L39

I will be patching this up in the next version. Just FYI this happens only on Mac OS, as we have multiple servers running Linux with Pocket Node in our infrastructure with no problem. Still it's a problem that needs to be solved. This same patch will fix the other issue you opened as well.
